### ISSUE TITLE
Migrate to Amazon Linux 2

### ISSUE THREAD

**Issue by tobodner** [awslabs/aws-lambda-cpp#101]
As per https://aws.amazon.com/blogs/compute/migrating-aws-lambda-functions-to-al2/ are there any known issues with using this runtime in the new environment?

**Comment by marcomagdy** [comment]
Nope. There shouldn't be any. Same guidance in the README applies.

**Comment by tobodner** [comment]
Thank you for the quick response. Feel free to close the issue.
