### ISSUE TITLE
Context reuse?

### ISSUE THREAD

**Issue by bobbyinthedark** [awslabs/aws-lambda-cpp#103]
Does context reuse as per https://docs.aws.amazon.com/lambda/latest/dg/runtimes-context.html work with this runtime? Considering switching our lambdas from Python to C++, and had found that in Python lambdas putting things like AWS SDK client objects and database connection objects in the global scope makes significant performance difference in the average case (warm starts)

**Comment by marcomagdy** [comment]
Check out the examples for how to do that in C++.
The dynamodb example creates a single client and passes its reference in the C++ lambda capture. That way you don't have to create the client for every invocation. https://github.com/awslabs/aws-lambda-cpp/blob/master/examples/dynamodb/main.cpp#L222
