### ISSUE TITLE
Application will not run with CMAKE3

### ISSUE THREAD

**Issue by RagavLilly** [awslabs/aws-lambda-cpp#109]
when i follow the guideline to run this aws using this guide https://aws.amazon.com/blogs/compute/introducing-the-c-lambda-runtime/

i always get error stating 

CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.9 or higher is required.  You are running version 3.6

is there a way to run this code using 3.6 ..? what are the changes required.

**Comment by marcomagdy** [comment]
You can always update to the latest CMake using a script like the one found here:
https://github.com/awslabs/aws-lambda-cpp/blob/aa351a6b037840f9edd7d90ef9e971317b7886e9/ci/docker/ubuntu-linux-18.04#L7

**Comment by kart1618** [comment]
@marcomagdy Thanks! Running the following, worked:
`wget -O cmake-install https://github.com/Kitware/CMake/releases/download/v3.13.0/cmake-3.13.0-Linux-x86_64.sh; \sh cmake-install --skip-license --prefix=/usr --exclude-subdirectory;`
