### ISSUE TITLE
Mac OS - Failed to identify, locate or package the loader. Please file an issue on Github!

### ISSUE THREAD

**Issue by saivempali** [awslabs/aws-lambda-cpp#114]
Hello,

I'm running the Cpp runtime on my Mac OS and I get the following error. It asks me to file an issue on Github. Below is the error upon running `make aws-lambda-package-demo`

```
[100%] Built target demo
Scanning dependencies of target aws-lambda-package-demo
Failed to identify, locate or package the loader. Please file an issue on Github!
make[3]: *** [CMakeFiles/aws-lambda-package-demo] Error 1
make[2]: *** [CMakeFiles/aws-lambda-package-demo.dir/all] Error 2
make[1]: *** [CMakeFiles/aws-lambda-package-demo.dir/rule] Error 2
make: *** [aws-lambda-package-demo] Error 2
```

Any help is appreciated!

Thanks!

**Comment by marcomagdy** [comment]
This library is not meant to be built on macOS. AWS Lambda runs on Linux, and this library makes assumptions on how Linux finds the dependencies of a given ELF executable.
This will not work on macOS.

**Comment by saivempali** [comment]
Thank you
