### ISSUE TITLE
format-check.sh uses non-existent command "NOT"

### ISSUE THREAD

**Issue by ilyash** [awslabs/aws-lambda-cpp#140]
https://github.com/awslabs/aws-lambda-cpp/blob/e73e472bd06fb959222646aa108e700c6e798028/ci/codebuild/format-check.sh#L7

consequently, the body of `if` is never invoked.

**Comment by paxsali** [comment]
I assume without knowing exactly that the author of that commit has `NOT` as an alias to `!` in his `.bashrc`.

```
alias NOT='!'

if NOT false; then
    echo "the if condition is true."
fi
```

This is the only explanation I can see plausible. Of course the NOT must be removed and replaced with a proper `!`.

**Comment by ilyash** [comment]
> I assume without knowing exactly that the author of that commit has `NOT` as an alias to `!` in his `.bashrc`.

Hmm. I thought aliases only supposed to work for interactive shells, not scripts...

> replaced with a proper `!`.

Most likely
