### ISSUE TITLE
typo in aws::http::response_code ?

### ISSUE THREAD

**Issue by gitusel** [awslabs/aws-lambda-cpp#145]
Just checking if this is not a typo in response.h:

../..

enum class response_code {
../..
    HTTP_VERSION_NOT_SUPPORTED = 505,
    VARIANT_ALSO_NEGOTIATES = 506,
    INSUFFICIENT_STORAGE = 506, <<<< 507?
    LOOP_DETECTED = 508,
../..

**Comment by kkarbowiak** [comment]
Indeed, looks like a typo. Good spot. Let me send a PR.
