### ISSUE TITLE
Is there a new release planned?

### ISSUE THREAD

**Issue by kkarbowiak** [awslabs/aws-lambda-cpp#171]
It's been almost two years since the last release and some improvements have been added.

Are there any plans for a new release?

**Comment by bmoffatt** [comment]
Yeah I can tag a release.

https://github.com/awslabs/aws-lambda-cpp/compare/v0.2.7...bmoffatt:aws-lambda-cpp:v0.2.8

@marcomagdy LMK if anything jumps out as a reason to tag this as `v0.3.0` rather than `v0.2.8`

**Comment by marcomagdy** [comment]
LGTM

**Comment by kkarbowiak** [comment]
Thank you both for handling this.
