### ISSUE TITLE
Embedding Python in AWS Lambda C++ runtime

### ISSUE THREAD

**Issue by NatxoM** [awslabs/aws-lambda-cpp#24]
I'm trying to embed Python in C++ using Pybind11. But my C++ program is using the AWS Lambda C++ runtime.

Everything compiles perfectly. However, when I upload the AWS Lambda package and invoke the Lambda function, it gives this error:

```
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'
```

Why?

[Question also asked here](https://stackoverflow.com/questions/54651111/embedding-python-in-aws-lambda-c-runtime)

**Comment by marcomagdy** [comment]
You need to know what shared libraries does python expect to exist and bundle those as well with your package.

**Comment by marcomagdy** [comment]
Let us know if you're still having problems.
