### ISSUE TITLE
How to add OpenCV support

### ISSUE THREAD

**Issue by PuneetKohli** [awslabs/aws-lambda-cpp#27]
I'm looking to add a C++ Lambda function that also has a dependency on OpenCV.

Unclear from the documentation what needs to be done to get this working on AWS Lambda's C++ runtime

**Comment by marcomagdy** [comment]
You need to build your Lambda function as you would build a CLI application for example.
So you need to link the OpenCV libraries to your function.

**Comment by PuneetKohli** [comment]
Hi @marcomagdy, which AWS Lambda documentation/example should I follow for this? I've been looking around for the correct set of instructions to follow but haven't been able to find the correct source.

**Comment by marcomagdy** [comment]
This is not Lambda specific information. You need to link the libraries like you do in any C++ program.
