### ISSUE TITLE
core dump at the end of lambda execution in cloudwatch

### ISSUE THREAD

**Issue by jwang01** [awslabs/aws-lambda-cpp#30]
03:22:53
REPORT RequestId: 89894b68-4c17-4ea6-b6e6-91bca83ae5b1	Duration: 1023.33 ms	Billed Duration: 1100 ms Memory Size: 3008 MB	Max Memory Used: 43 MB

03:22:53
RequestId: 89894b68-4c17-4ea6-b6e6-91bca83ae5b1 Error: Runtime exited with error: signal: segmentation fault (core dumped) Runtime.ExitError

**Comment by marcomagdy** [comment]
Do you have any data that points to the C++ Lambda runtime causing this segfault? Did you rule out your own code?

**Comment by jwang01** [comment]
Our C++ lambda runtime seems getting the job done correctly, and I double check the results posted back to S3, everything seems working for us. As you can see the error says  "Runtime.ExitError", which might be in the lambda container side.

**Comment by marcomagdy** [comment]
Runtime.ExitError means the process terminated rather than exit gracefully. Which means, it never sent the response. As in `invocation_response::success(...)` or `invocation_response::failure(...)` was not called.

This would happen for example if you pass a `nullptr` to one of those functions.

**Comment by jwang01** [comment]
I think that's it. Thanks!
