### ISSUE TITLE
Failure while building package

### ISSUE THREAD

**Issue by scm-ns** [awslabs/aws-lambda-cpp#32]
When I run the make aws-lambda-package-hello command. I see this error. 

Ubuntu 16.04

CMakeFiles/aws-lambda-package-hello.dir/build.make:57: recipe for target 'CMakeFiles/aws-lambda-package-hello' failed
make[3]: *** [CMakeFiles/aws-lambda-package-hello] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/aws-lambda-package-hello.dir/all' failed
make[2]: *** [CMakeFiles/aws-lambda-package-hello.dir/all] Error 2
CMakeFiles/Makefile2:74: recipe for target 'CMakeFiles/aws-lambda-package-hello.dir/rule' failed
make[1]: *** [CMakeFiles/aws-lambda-package-hello.dir/rule] Error 2
Makefile:118: recipe for target 'aws-lambda-package-hello' failed
make: *** [aws-lambda-package-hello] Error 2

**Comment by marcomagdy** [comment]
I'm unable to reproduce this problem.
Can you provide steps to reproduce it?

**Comment by marcomagdy** [comment]
Needed more information.
