### ISSUE TITLE
Logging not showing in watchcloud

### ISSUE THREAD

**Issue by redspart** [awslabs/aws-lambda-cpp#36]
When running the following code we are attempting to get the AWS_LOGSTREAM_TRACE to show-up in the cloudwatch log instance to no avail. The odd part is when we invoke the lambda multiple times in quick succession it does write a log with the trace in it. 

We modified the code in your S3 example to just print to the log but we didn't include all of our functions in this post. We are having issues logging with the s3 example as well.

#### Build
```bash
cmake . -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=~/install
aws lambda create-function --function-name lambda-demo --role arn:aws:iam::<redacted>:role/lambda-demo --runtime provided --timeout 15 --memory-size 128 --handler demo --zip-file fileb://memoryreader.zip
```

#### Code
```c++
std::string open_and_read_file(
    Aws::S3::S3Client const& client,
    Aws::String const& bucket,
    Aws::String const& key
);

std::string get_memory_consumption();

char const TAG[] = "LAMBDA_ALLOC";

static invocation_response my_handler(invocation_request const& req, Aws::S3::S3Client const& client)
{
    using namespace Aws::Utils::Json;
    JsonValue json(req.payload);
    if (!json.WasParseSuccessful()) {
        return invocation_response::failure("Failed to parse input JSON", "InvalidJSON");
    }

    auto v = json.View();

    get_memory_consumption();
    AWS_LOGSTREAM_TRACE(TAG, "Hello-World!");
    if (!v.ValueExists("s3bucket") || !v.ValueExists("s3key") ||
        !v.GetObject("s3bucket").IsString() || !v.GetObject("s3key").IsString()) {
        return invocation_response::failure("Missing input value s3buckets or 3key " , "InvalidJSON");
    }

    if (v.ValueExists("s3bucket") || v.ValueExists("s3key") ||
        v.GetObject("s3bucket").IsString() || v.GetObject("s3key").IsString()) {
        std::string toReturn = get_memory_consumption();
        return invocation_response::success(toReturn, "application/json");
    }

    return invocation_response::failure("failure", "DownloadFailure");
}

std::function<std::shared_ptr<Aws::Utils::Logging::LogSystemInterface>()> GetConsoleLoggerFactory()
{
    return [] {
        return Aws::MakeShared<Aws::Utils::Logging::ConsoleLogSystem>(
            "console_logger", Aws::Utils::Logging::LogLevel::Trace);
    };
}

int main()
{
    using namespace Aws;

    SDKOptions options;
    options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
    options.loggingOptions.logger_create_fn = GetConsoleLoggerFactory();
    InitAPI(options);
    {
        Client::ClientConfiguration config;
        config.region = Aws::Environment::GetEnv("AWS_REGION");
        config.caFile = "/etc/pki/tls/certs/ca-bundle.crt";

        auto credentialsProvider = Aws::MakeShared<Aws::Auth::EnvironmentAWSCredentialsProvider>(TAG);
        S3::S3Client client(credentialsProvider, config);
        auto handler_fn = [&client](aws::lambda_runtime::invocation_request const& req) {
            return my_handler(req, client);
        };
        run_handler(handler_fn);
    }
    ShutdownAPI(options);
    return 0;
}
```

#### Things we have tried:
1. Changing the `LogLevel::Trace` to `LogLevel::Debug` and any values in between
2. Changing `AWS_LOGSTREAM_TRACE` to `AWS_LOGSTREAM_FATAL` and any values in between

Best,
Christian

**Comment by marcomagdy** [comment]
I suspect that is because the AWS SDK [buffers the log messages ](https://github.com/aws/aws-sdk-cpp/blob/af8089f6277b8fec93c55a815c724444bd159a13/aws-cpp-sdk-core/source/utils/logging/DefaultLogSystem.cpp#L28)(up to 100) before writing them to the underlying device, whether that is a file or stdout. Which makes sense why you start seeing the logs if you invoke the lambda function multiple times.

Can you create a GitHub issue on the AWS SDK repo? we need to either make that number configurable or add a flush method to the logger interface.
FWIW, I'm one of the maintainers of the AWS SDK for C++, so I will make sure it gets implemented.

**Comment by redspart** [comment]
@marcomagdy Thanks for the suggestion. I agree with you that having the ability to set that number will help out. I have opened an issue on that repo [here](https://github.com/aws/aws-sdk-cpp/issues/1140)
