### ISSUE TITLE
Question on debugging the crashing

### ISSUE THREAD

**Issue by ukulililixl** [awslabs/aws-lambda-cpp#40]
I want to debug the program locally and it is suggested that we can run our code locally in Docker container. I run ```$ docker run -v /tmp:/tmp -it --security-opt seccomp=unconfined amazonlinux:2017.03``` and then feel confused how to run my code locally in the container. Does it mean that I need to build my project inside the container, upload it to my aws lambda and trigger my lambda inside the container? Or I can just run my code inside the container? Thanks!

**Comment by marcomagdy** [comment]
copy the zip package that you normally upload to Lambda over to the container, unzip the package and run your executable by invoking `./bootstrap`.
Before running the bootstrap script, you should modify it in a way to re-route the execution path from invoking `run_handler(...)`. You can do that by passing some argument to your executable that results in running your actual function right away bypassing the communication with the Lambda backend.

```cpp
static invocation_response my_handler(invocation_request const& req)
{
    // extract data from req
    // run function foo
    // invocation_response::success(...)  
}

int main(int argc, char** argv)
{
    if (argc > 1) {
     // run function foo directly
    } else {
      run_handler(my_handler);
    }
    return 0;
}
```

SAM CLI support should be coming soon that will make this whole thing 10x easier.
Let me know if you still have questions.
