### ISSUE TITLE
PKG_LD is empty, lambda cannot run

### ISSUE THREAD

**Issue by krk** [awslabs/aws-lambda-cpp#45]
On Ubuntu 18.04, when I follow the steps in https://aws.amazon.com/blogs/compute/introducing-the-c-lambda-runtime/ the lambda fails to run with the log:

```
START RequestId: 8ea03c41-6ca2-4e5a-b63c-d3461c8a777c Version: $LATEST
/var/task/bootstrap: line 4: /var/task/lib/: Is a directory
/var/task/bootstrap: line 4: exec: /var/task/lib/: cannot execute: Is a directory
END RequestId: 8ea03c41-6ca2-4e5a-b63c-d3461c8a777c
REPORT RequestId: 8ea03c41-6ca2-4e5a-b63c-d3461c8a777c Duration: 153.26 ms Billed Duration: 200 ms Memory Size: 128 MB Max Memory Used: 12 MB 
```

When I replace `$PKG_LD` at https://github.com/awslabs/aws-lambda-cpp/blob/1dccd2af06d8c76d11ffb73f38a1999aaba634da/packaging/packager#L141 with loader name `ld-linux-x86-64.so.2`, the lambda runs successfully.  

When I move the if block at line 116 to line 112, it works for me:

https://github.com/awslabs/aws-lambda-cpp/blob/1dccd2af06d8c76d11ffb73f38a1999aaba634da/packaging/packager#L113-L121

**Comment by marcomagdy** [comment]
I really need to add CI for ubuntu

**Comment by marcomagdy** [comment]
Fixed now. Thanks for reporting the issue.
