### ISSUE TITLE
The revised CMakeList.txt does not work

### ISSUE THREAD

**Issue by miryee** [awslabs/aws-lambda-cpp#48]
aws-lambda-cpp builds using the previous version of CMakeList.txt with:
`target_link_libraries(${PROJECT_NAME} PRIVATE ${CURL_LIBRARIES})`

And produces errors using the newly release version with:
`target_link_libraries(${PROJECT_NAME} PRIVATE CURL::libcurl)`

The output for the second version is:
```
-- Configuring done
CMake Error at CMakeLists.txt:13 (add_library):
  Target "aws-lambda-runtime" links to target "CURL::libcurl" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:13 (add_library):
  Target "aws-lambda-runtime" links to target "CURL::libcurl" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

-- Generating done
-- Build files have been written to: /github/aws-lambda-cpp/built
```

**Comment by marcomagdy** [comment]
What version of CMake are you using?

**Comment by marcomagdy** [comment]
nvm, I'm able to reproduce it

**Comment by marcomagdy** [comment]
I will revert the change. Meanwhile, I recommend using the latest CMake. And since apt never provides the latest version (unlike Homebrew), you can follow the steps here https://askubuntu.com/a/865294 to upgrade.
Note that upgrading CMake is almost always a good idea since it's not a library on which other applications depend on. So, you will not break anything by upgrading.

**Comment by miryee** [comment]
I am using cmake version 3.10.2-1ubuntu2, which is the latest version for ubuntu.

**Comment by mrahman4** [comment]
I've the same issue. Should I use the commit#0bcaf3d?

**Comment by marcomagdy** [comment]
You can. Or better yet upgrade the CMake version on your machine?
see https://github.com/awslabs/aws-lambda-cpp/blob/master/ci/docker/ubuntu-linux-18.04#L5
