### ISSUE TITLE
Additional getting-started examples 

### ISSUE THREAD

**Issue by mfjonker** [awslabs/aws-lambda-cpp#57]
I've been in contact with the AWS support to get help with setting up a simple AWS Lambda function with JSON inputs/outputs received/send via API Gateway. The support officer lacked the required C++ expertise and could only find three examples, one being extremely simple and the other ones pretty advanced. For both us this, this was insufficient to figure out how to define the required handler function that handles the input/output of the C++ Lambda's. Hence the support officer suggested to open an issue here and ask you (as C++ Runtime developers) to perhaps create a few additional examples. The C++ equivalents of the NodeJS code used in the API Gateway + Lambda tutorials would e.g. be great:

1) https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-create-api-as-simple-proxy-for-lambda.html
2) https://docs.aws.amazon.com/apigateway/latest/developerguide/getting-started-lambda-non-proxy-integration.html

These are a bit more elaborate as the Hello World example in the C++ Runtime Blog (https://aws.amazon.com/blogs/compute/introducing-the-c-lambda-runtime/)
but still very simple to understand and hence informative. Great to explain how to receive inputs, use the C++ SDK to parse the JSON, get the inputs, return a serialized JSON or error code, etc. 

Would something like this be possible?

**Comment by stuta** [comment]
Is there an example how to use this with websockets? Is it possible? Where is callback?

This node Lambda function works with websockets:

```js
exports.handler = function (event, context, callback) {
  callback(null, {
    statusCode: 200,
    body: "Connected"
  })
}
```

**Comment by jghankins** [comment]
I agree that a simple example that includes return values would be useful.

**Comment by ortymd** [comment]
Is there maybe a way to assign this to someone for proper coordination? I failed to assign this to myself. Apparently, pull collaborators are not allowed to assign issues...

**Comment by marcomagdy** [comment]
@ortymd do you want to work on this issue? if yes, please do, I'll assign it to you.
Also, a PR would work

**Comment by ortymd** [comment]
I'll submit a PR once I have something. 
I think that having someone responsible for such issues helps avoiding duplicate work(examples)
@marcomagdy, yes please assign.
