### ISSUE TITLE
"Process exited before completing request" for large payloads

### ISSUE THREAD

**Issue by Coderik** [awslabs/aws-lambda-cpp#60]
Hello!

I am trying to pass a base64-encoded image as a payload to a handler. Everything works fine for small images (say 4kb), however, for larger images (60kb, yet still below the limit) I always get "Process exited before completing request" error.

I've made tests with a simple function that just returns the payload:
```
using namespace aws::lambda_runtime;

invocation_response handler(invocation_request const &request)
{
	return invocation_response::success(request.payload, "application/json");
}

int main(int argc, char *argv[])
{
	run_handler(handler);
	return 0;
}
```

I've checked the CloudWatch logs:
```
13:10:04 START RequestId: a6f64093-b2da-4cfd-80e1-2993b0b2d618 Version: $LATEST
13:10:04 [DEBUG] [1567429804774] LAMBDA_RUNTIME CURL DBG: Closing connection 1
13:10:04 [DEBUG] [1567429804774] LAMBDA_RUNTIME Completed request to http://127.0.0.1:9001/2018-06-01/runtime/invocation/next
13:10:04 [DEBUG] [1567429804774] LAMBDA_RUNTIME CURL returned error code 56 - Failure when receiving data from the peer
13:10:04 [ERROR] [1567429804774] LAMBDA_RUNTIME Failed to get next invocation. No Response from endpoint
13:10:04 [DEBUG] [1567429804774] LAMBDA_RUNTIME Making request to http://127.0.0.1:9001/2018-06-01/runtime/invocation/next
13:10:04 [DEBUG] [1567429804774] LAMBDA_RUNTIME CURL DBG: Hostname in DNS cache was stale, zapped
13:10:04 [DEBUG] [1567429804775] LAMBDA_RUNTIME CURL DBG: Trying 127.0.0.1...
13:10:04 [DEBUG] [1567429804775] LAMBDA_RUNTIME CURL DBG: TCP_NODELAY set
13:10:04 [DEBUG] [1567429804775] LAMBDA_RUNTIME CURL DBG: Connected to 127.0.0.1 (127.0.0.1) port 9001 (#2)
13:10:04 [DEBUG] [1567429804775] LAMBDA_RUNTIME CURL DBG: GET /2018-06-01/runtime/invocation/next HTTP/1.1
13:10:04 Host: 127.0.0.1:9001
13:10:04 Accept: */*
13:10:04 
13:10:04 END RequestId: a6f64093-b2da-4cfd-80e1-2993b0b2d618
13:10:04 REPORT RequestId: a6f64093-b2da-4cfd-80e1-2993b0b2d618	Duration: 38.23 ms	Billed Duration: 100 ms	Memory Size: 3008 MB	Max Memory Used: 45 MB	XRAY TraceId: -5d6d14ac-af92232da896727996439756	SegmentId: 377737ff72691de0	Sampled: true
13:10:04 RequestId: a6f64093-b2da-4cfd-80e1-2993b0b2d618 Process exited before completing request
13:10:04 [INFO] [1567429804963] LAMBDA_RUNTIME Initializing the C++ Lambda Runtime version 0.2.4
13:10:04 [DEBUG] [1567429804963] LAMBDA_RUNTIME LAMBDA_SERVER_ADDRESS defined in environment as: 127.0.0.1:9001
13:10:04 [DEBUG] [1567429804978] LAMBDA_RUNTIME Making request to http://127.0.0.1:9001/2018-06-01/runtime/invocation/next
13:10:04 [DEBUG] [1567429804978] LAMBDA_RUNTIME CURL DBG: Trying 127.0.0.1...
13:10:04 [DEBUG] [1567429804978] LAMBDA_RUNTIME CURL DBG: TCP_NODELAY set
13:10:04 [DEBUG] [1567429804978] LAMBDA_RUNTIME CURL DBG: Connected to 127.0.0.1 (127.0.0.1) port 9001 (#0)
13:10:04 [DEBUG] [1567429804978] LAMBDA_RUNTIME CURL DBG: GET /2018-06-01/runtime/invocation/next HTTP/1.1
13:10:04 Host: 127.0.0.1:9001
13:10:04 Accept: */*
``` 
It looks like the request to /2018-06-01/runtime/invocation/next somehow kills the runtime.
From my tests this happens for payloads larger than 7759 bytes. Slightly bigger payloads sometimes get through, which is even more confusing. Maybe some timeout somewhere?

Do you have any idea why this might happen? Or some suggestions how I could dig deeper?

**Comment by marcomagdy** [comment]
I've opened a ticket with the Lambda backend team to get more details. I'll update you here as I get more information.

**Comment by Coderik** [comment]
Thank you! I've run out of ideas.

**Comment by bowie7070** [comment]
I have hit the same problem. Everything seems to be fine when I send only a 3KB fragment of my data but when I send everything (about 1.4MB) I get the above error.

**Comment by marcomagdy** [comment]
The Lambda backend team is actively looking into this.

**Comment by marcomagdy** [comment]
Can you provide the libcurl version you're linking to and the distro version you're using?

In the past we've seen bugs that were caused by a some libcurl versions (unfortunately sometimes it's the version shipping with the distro).

**Comment by Coderik** [comment]
libcurl version is 7.47.0
And I am on Ubuntu 16.04

**Comment by marcomagdy** [comment]
We're unable to reproduce the problem on Ubuntu 18.04.
Can you try either upgrading the system's libcurl or building the latest released version from source?

**Comment by bowie7070** [comment]
I also had CURL 7.47.0. After I upgraded to CURL 7.65.3 the has gone away. I notice that CURL provides a file curlver.h with defines of the form:

/* The numeric version number is also available "in parts" by using these
   defines: */
#define LIBCURL_VERSION_MAJOR 7
#define LIBCURL_VERSION_MINOR 65
#define LIBCURL_VERSION_PATCH 3

It might be worth adding a cmake configure or compile time check in the runtime that the version of curl is high enough to avoid this problem.

**Comment by Coderik** [comment]
I confirm that it works with libcurl 7.65.3

**Comment by marcomagdy** [comment]
@bowie7070 I think I've had enough problems from sketchy libcurl builds that I will work on bundling a good, slimmed-down build of libcurl with this runtime.
It will be an option in CMake.
Thanks for reporting back that it works now.
