### ISSUE TITLE
Read timeout on endpoint URL

### ISSUE THREAD

**Issue by bowie7070** [awslabs/aws-lambda-cpp#61]
I have a lambda function that is performs a simulation. I have an input that controls the number of simulation paths and the time taken increases linearly in the number of paths. For 2000 paths my simulation takes 35 seconds.

```
$ time aws lambda invoke --function-name "calculate" --payload "$(cat lambda-fail-0.json)" out.txt ; cat out.txt
{
    "StatusCode": 200,
    "ExecutedVersion": "$LATEST"
}

real    0m35.258s
user    0m0.376s
sys     0m0.084s

```

If I double the number of simulation paths, I expected for the invocation to take about 70 seconds.  I get a timeout:

```
$ time aws lambda invoke --function-name "calculate" --payload "$(cat lambda-fail-0.json)" out.txt ; cat out.txt

Read timeout on endpoint URL: "https://lambda.ap-southeast-2.amazonaws.com/2015-03-31/functions/gen_MC_calculate_compound/invocations"

real    5m12.670s
user    0m0.489s
sys     0m0.094s
```

Any advice on what is going wrong and how to further diagnose the issue would be greatly appreciated.

**Comment by marcomagdy** [comment]
I need more information.
What do you see when you look at CloudWatch logs? does the function finish? (this is to debug why the cli is timing out).

Are you running multiple threads? are there mutexes and locks? Those don't scale linearly..
What is the behavior if you run the code locally? does it meet the expectation of linear progression?

**Comment by bowie7070** [comment]
I am running with multiple threads. No mutexes or locks because the simulation is embarrassingly parallel. I disabled the use of threads when running on Lambda and that has resolved the problem. Appreciate the help.

Maybe I missed this in the documentation but if it is not there, perhaps it would be worth adding something about threading to the introductory material. Or maybe even a separate blog post about how to do division of work with Lambda.

Anyway thanks again for the attention.

**Comment by marcomagdy** [comment]
There’s nothing that prevents you from using threads. They work just fine. You might be running “too many” threads.

**Comment by bowie7070** [comment]
Hmmm. Only 8 threads I think.

**Comment by benminer** [comment]
Getting this while invoking other Lambdas from a Lambda - although it isn't consistent. Just every now and then. No multithreading happening, either.

**Comment by devops-chinmay** [comment]
Just try to add **--cli-read-timeout 0**... and see if waiting little longer will resolve your issue!
