### ISSUE TITLE
package failed to find loader

### ISSUE THREAD

**Issue by jmanno1** [awslabs/aws-lambda-cpp#63]
The following error happens when following the tutorial for aws-lambda-package-demo using Manjaro Linux. A temporary solution was found.

`Failed to identify, locate or package the loader. Please file an issue on Github!
make[3]: *** [CMakeFiles/aws-lambda-package-demo.dir/build.make:57: CMakeFiles/aws-lambda-package-demo] Error 1
`

Because Manjaro is not supported, the functions to find libc did not properly trigger, which stopped the loader from being found.

The temporary solution was to modify packager:59 and change "Arch Linux" to "Manjaro Linux". This is because Manjaro is a derivative of Arch and also has the pacman utility installed.

**Comment by marcomagdy** [comment]
I think I need to come up with a list of Linux distributions that I'd be willing to support. There will always be another Linux distro that the packager does not work for. Thanks for submitting this issue, I'm sure it will help someone else running into the same problem.

**Comment by jmanno1** [comment]
No problem. The error message asked for an issue submission so it was the least I could do.
