### ISSUE TITLE
scanning aws-lambda-runtime dependencies stuck at 60%

### ISSUE THREAD

**Issue by QuiHan** [awslabs/aws-lambda-cpp#71]
After upgrading the cmake minimum version to 3.9, it stucks at 60% progress when building CXX object CMakeFiles/aws-lambda-runtime.dir/src/backward.cpp.o

![image](https://user-images.githubusercontent.com/20399155/70282470-b736d480-1822-11ea-970a-d63f016fecef.png)

**Comment by marcomagdy** [comment]
That's odd.
Have you tried building it on a different machine to rule out any setup you have that might be causing that?

It builds fine on the CI build machines and on all of our development machines as well.

**Comment by QuiHan** [comment]
Ya, it is odd. I did interrupt the scan but things ate still working fine. Might be something to do with my VM. 

Cheers.

**Comment by marcomagdy** [comment]
I'm a little confused. Is this still an issue you're running into? Are you able to reproduce on different machines?

**Comment by ortymd** [comment]
Hi all,
Failed to reproduce this on
`dpoliaru@host:~/repos/aws-lambda-cpp/build$ uname -a
Linux host 5.3.0-24-generic #26-Ubuntu SMP Thu Nov 14 01:33:18 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
dpoliaru@host:~/repos/aws-lambda-cpp/build$ 
` 
with cmake:
`dpoliaru@host:~/repos/aws-lambda-cpp/build$ cmake --version
cmake version 3.13.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).
dpoliaru@host:~/repos/aws-lambda-cpp/build$ 
`
here the output:
`dpoliaru@host:~/repos/aws-lambda-cpp/build$ cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/lambda-install
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.65.3") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dpoliaru/repos/aws-lambda-cpp/build
dpoliaru@host:~/repos/aws-lambda-cpp/build$ make
Scanning dependencies of target aws-lambda-runtime
[ 20%] Building CXX object CMakeFiles/aws-lambda-runtime.dir/src/logging.cpp.o
[ 40%] Building CXX object CMakeFiles/aws-lambda-runtime.dir/src/runtime.cpp.o
[ 60%] Building CXX object CMakeFiles/aws-lambda-runtime.dir/src/backward.cpp.o
[ 80%] Building CXX object CMakeFiles/aws-lambda-runtime.dir/version.cpp.o
[100%] Linking CXX static library libaws-lambda-runtime.a
[100%] Built target aws-lambda-runtime
dpoliaru@host:~/repos/aws-lambda-cpp/build$
`

**Comment by QuiHan** [comment]
Hi all,

I think it might be something to do with my machine. I’ll observe it and close this for now.

Cheers.
