### ISSUE TITLE
aws-lambda/lib/aws-lambda-runtime/cmake/packager returns error when copying symlink on Ubuntu 19.10

### ISSUE THREAD

**Issue by ortymd** [awslabs/aws-lambda-cpp#73]
I recently hit this issue when working on the PR with examples for lambda.
Basically, cp command here:
/home/dpoliaru/aws-lambda/lib/aws-lambda-runtime/cmake/packager:line 139
`
...
139         cp --no-dereference "$i" "$PKG_DIR/lib" 
...
`
fails with:
`
cp: cannot create symbolic link 'tmp/lib/libBrokenLocale.so.1': Operation not permitted
`
And the zip archive is not created. I simply followed intro to [cpp-runtime](https://aws.amazon.com/blogs/compute/introducing-the-c-lambda-runtime/) examples.

Finally, I managed to build the archive by ommitng symbolic links being copied to `tmp/lib`
Here is the diff:

![packager-no-symlinks](https://user-images.githubusercontent.com/22126392/72051992-f26a6e80-32cc-11ea-94e3-9dad4c0c096e.png)

Post recommends using Amazon Linux, but I already had an ubuntu 19.10 vm, so decided to try it on this machine.

Please let me know whether this is an issue or I'm just missing something....

**Comment by marcomagdy** [comment]
I will try to reproduce it.
Operation not permitted sounds like a permissions issue, which is odd!
does that happen with just that file or many of them?

**Comment by ortymd** [comment]
I assume that this is NOT a permission error. Have a look:

![Screenshot from 2020-01-15 19-59-17](https://user-images.githubusercontent.com/22126392/72458614-92466180-37d1-11ea-95fa-9427b619d321.png)

"Operation not permmited" apparently means that OS does not know how to do this. These are different errors. "Permission denied" is NOT "Operation not permitted"

Thus maybe Amazon Linux knows how to copy these links and vanilla Ubuntu does not...

**Comment by marcomagdy** [comment]
does that happen with just that file or many of them?
It's worth noting that it works fine with Ubuntu 18.04 LTS (that's the one used in the CI). I'm curious what changed in Ubuntu 19

**Comment by marcomagdy** [comment]
I just tried to reproduce the issue in a docker container running Ubuntu 19.10 and I couldn't.
It works and built the zip file just fine.
Can you make sure that `libBrokenLocale.so.1` is a valid symlink on your system. On a fresh docker container running ubuntu 19.10 I have the following:
```
/lib/x86_64-linux-gnu/libBrokenLocale.so -> /lib/x86_64-linux-gnu/libBrokenLocale.so.1
/lib/x86_64-linux-gnu/libBrokenLocale.so.1 -> libBrokenLocale-2.30.so
```

**Comment by ortymd** [comment]
Yes. The link is fine. The reason is that /home/dpoliaru/test/aws-lambda/build directory on this VM is a shared directory with host machine(with Windows 10). Ownership is `root:vboxsf`, but even with sudo I fail to copy links. Apparently there are some restrictions on the OS level, but I cannot specify more details as of now. I think this can be closed.
