### ISSUE TITLE
Failed to identify, locate or package the loader

### ISSUE THREAD

**Issue by Tombmyst** [awslabs/aws-lambda-cpp#77]
Hi,

I went through the example in the documentation. Everything goes fine, except when I enter the command "make aws-lambda-package-demo", which gives me this error:
`[100%] Built target demo

Scanning dependencies of target aws-lambda-package-demo

Failed to identify, locate or package the loader. Please file an issue on Github!

make[3]: *** [CMakeFiles/aws-lambda-package-demo.dir/build.make:57: CMakeFiles/aws-lambda-package-demo] Error 1

make[2]: *** [CMakeFiles/Makefile2:104: CMakeFiles/aws-lambda-package-demo.dir/all] Error 2

make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/aws-lambda-package-demo.dir/rule] Error 2

make: *** [Makefile:131: aws-lambda-package-demo] Error 2
`

I'm running on Manjaro Linux 5.4.2 and have all the required dependencies installed.

Thank you!

**Comment by Tombmyst** [comment]
OK just saw that you don't support Manjaro, I will use a docker instead

**Comment by marcomagdy** [comment]
I'd love to add support for Majaro.. PR?
