### ISSUE TITLE
packager includes a mix of 64-bit and 32-bit libraries on Fedora 31

### ISSUE THREAD

**Issue by markus90206** [awslabs/aws-lambda-cpp#83]
I am following the instructions from `README.md` to build the `demo.zip` on Fedora 31 (`x86_64`), i.e., I am not running custom code yet (besides renaming the binary). Unfortunately, I am getting the following error when calling the function.

    /var/task/bin/incoming-mail: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /var/task/lib/libstdc++.so.6)

As it turns out, the `packager` script gets the list of shared objects for `glibc` from `rpm`.

```
$ cat /etc/fedora-release 
Fedora release 31 (Thirty One)
$ rpm --query --list glibc | sed -E '/\.so$|\.so\.[0-9]+$/!d'                
/lib64/ld-2.30.so
/lib64/ld-linux-x86-64.so.2
/lib64/libBrokenLocale-2.30.so
/lib64/libBrokenLocale.so.1
/lib64/libSegFault.so
/lib64/libanl-2.30.so
/lib64/libanl.so.1
/lib64/libc-2.30.so
/lib64/libc.so.6
[...]
/usr/lib64/audit/sotruss-lib.so
/usr/lib64/gconv/ANSI_X3.110.so
[...]
/lib/ld-2.30.so
/lib/ld-linux.so.2
/lib/libBrokenLocale-2.30.so
/lib/libBrokenLocale.so.1
/lib/libSegFault.so
/lib/libanl-2.30.so
/lib/libanl.so.1
/lib/libc-2.30.so
/lib/libc.so.6
[...]
/usr/lib/audit/sotruss-lib.so
/usr/lib/gconv/ANSI_X3.110.so
[...]
```

This list includes 64-bit and 32-bit versions of `glibc`'s shared objects.

I unpacked the resutling zip-file and it indeed contains 32-bit libraries.

```
$ unzip path/to/demo.zip
$ cd lib/
$ for i in * ; do file ${i} ; done | awk '{ print $1 $3 }'
[...]
libc-2.30.so:32-bit
[...]
libdl-2.30.so:32-bit
[...]
libgcc_s.so.1:64-bit
[...]
```

To omit all 32-bit libraries, one can omit all shared objects that are in directories containing the string `lib/`. 

```
diff --git a/packaging/packager b/packaging/packager
index 32b2db0..497d0ae 100755
--- a/packaging/packager
+++ b/packaging/packager
@@ -74,7 +74,7 @@ function package_libc_via_dpkg() {
 function package_libc_via_rpm() {
     if type rpm > /dev/null 2>&1; then
        if [[ $(rpm --query --list glibc | wc -l) -gt 1 ]]; then
-           rpm --query --list glibc | sed -E '/\.so$|\.so\.[0-9]+$/!d'
+           rpm --query --list glibc | sed -E '/\.so$|\.so\.[0-9]+$/!d' | grep -Pv 'lib/'
        fi
     fi
 }
```

I don't want to assess if this is an acceptable solution, but I confirmed that the Lambda function from a newly packaged `demo.zip` works as expected.

```
$ aws lambda invoke --function-name demo --payload '{"answer":42}' output.txt
{
    "StatusCode": 200,
    "ExecutedVersion": "$LATEST"
}
```

**Comment by marcomagdy** [comment]
That makes sense.
Can you create a pull request with the changes?
Also use the verbose versions of the flags as in:` grep --invert-match`

**Comment by markus90206** [comment]
> Can you create a pull request with the changes?
> Also use the verbose versions of the flags as in:` grep --invert-match`

I created the pull request and changed `grep --inverted-match lib/` to `grep lib64` as the result is the same, but cleaner to read.
