### ISSUE TITLE
Update to 0.2.5 from 0.2.4 results in linker "undefined reference" error

### ISSUE THREAD

**Issue by bmacphee** [awslabs/aws-lambda-cpp#86]
Is there anything obvious I should be looking for in my own project that would cause this?
versions for reference: CMake version 3.13.3, gcc 8.3.0

In function `lambda_handler(aws::lambda_runtime::invocation_request const&)':
: undefined reference to `aws::lambda_runtime::invocation_response::success(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

(and many others including aws::lambda_runtime::run_handler)

**Comment by bmacphee** [comment]
Ok, it's the link-time optimization.  I see there's a flag now to disable this, which actually comes in handy until I can figure out why my build environment behaves this way.
https://github.com/awslabs/aws-lambda-cpp/commit/c93cfe64c2e68ef691d1d9904d7f40453be0d876#diff-af3b638bc2a3e6c650974192a53c7291

**Comment by marcomagdy** [comment]
if you have more details on how to reproduce this issue, please share them.

**Comment by bmacphee** [comment]
Our build is not doing anything out of the ordinary.  We use a docker-based build installs a newer version of gcc on top of Ubuntu 18.04.  It grabs the aws dependencies including aws-lambda-cpp and builds our lambda project as instructed in the README.md for cmake.

Since the ENABLE_LTO flag is not in a new tag yet, I've decided to only upgrade to 0.2.4 until that new release becomes available.

**Comment by bmacphee** [comment]
I have to correct my above assertions.  Our build was actually switched to clang6 by some recent changes to our docker image so my claim that we were using gcc8.3 is actually wrong.  It looks like the LTO support does work with cmake on gcc, but I can't fully finish testing this right now.  I'd suggest this issue can be closed for now, but if I have time to reproduce the problem with a more standard build set up, I may be able to reopen it with more details.
