### ISSUE TITLE
Windows 10 WLSL, AmazonWSL and sample Lambda function

### ISSUE THREAD

**Issue by genifycom** [awslabs/aws-lambda-cpp#88]
I have created an Amazon Linux 2 environment for Windows 10 WSLS using https://github.com/yosukes-dev/AmazonWSL

The environment appears fine and I successfully ran through most of the instructions on https://aws.amazon.com/blogs/compute/introducing-the-c-lambda-runtime/

I have gcc version 7.3.1 20180712, cmake3 version 3.13.1, GNU Make 3.82

I successfully compiled the aws-lambda runtime.

Now I want to complete the last part of the sample Lambda C++ function (step 4)
The cmake3 runs without errors

-bash-4.2# cmake3 .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=~/out
-- The CXX compiler identification is GNU 7.3.1
-- Check for working CXX compiler: /usr/bin/gcc
-- Check for working CXX compiler: /usr/bin/gcc -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CURL: /usr/lib64/libcurl.so (found version "7.61.1")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/aws-lambda-cpp/build/hello-cpp-world/build

But the make shows lots of errors.

Scanning dependencies of target hello
[ 50%] Building CXX object CMakeFiles/hello.dir/main.cpp.o
[100%] Linking CXX executable hello
CMakeFiles/hello.dir/main.cpp.o: In function `void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*>(char const*, char const*, std::forward_iterator_tag) [clone .isra.19]':
main.cpp:(.text+0x51): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
CMakeFiles/hello.dir/main.cpp.o: In function `my_handler(aws::lambda_runtime::invocation_request const&)':
main.cpp:(.text+0xe0): undefined reference to `operator delete(void*)'
main.cpp:(.text+0xf4): undefined reference to `operator delete(void*)'
main.cpp:(.text+0x114): undefined reference to `operator delete(void*)'
main.cpp:(.text+0x132): undefined reference to `operator delete(void*)'
...

Are there more up to date instructions for the page https://aws.amazon.com/blogs/compute/introducing-the-c-lambda-runtime/

Thank you

**Comment by marcomagdy** [comment]
The instructions are up to date.
Judging by the error, it seems like the linker is unable to find `libstdc++.so`. Your Linux distro/setup is likely broken.
