### ISSUE TITLE
Logging with cpp lambda

### ISSUE THREAD

**Issue by jgcrunden** [awslabs/aws-lambda-cpp#90]
Hello,
Just wondering if I could get some clarification on how the cpp lambda runtime works, namely the logging aspect.
Using your [S3 example](https://github.com/awslabs/aws-lambda-cpp/tree/master/examples/s3) as a basis, I tried creating my own "Hello world" lambda function:
```
#include <aws/lambda-runtime/runtime.h>

#include <aws/core/Aws.h>
#include <aws/core/utils/logging/ConsoleLogSystem.h>
#include <aws/core/utils/logging/LogLevel.h>
#include <aws/core/utils/logging/LogMacros.h>
#include <aws/core/client/ClientConfiguration.h>
#include <aws/core/auth/AWSCredentialsProvider.h>
#include <aws/core/platform/Environment.h>

using namespace aws::lambda_runtime;
char const TAG[] = "lambda logger";

invocation_response my_handler(invocation_request const& request)
{
    AWS_LOGSTREAM_INFO(TAG, "Some test logging");
    return invocation_response::success("Lambda ran successfully", "application/json");
}

std::function<std::shared_ptr<Aws::Utils::Logging::LogSystemInterface>()> GetConsoleLoggerFactory()
{
    return [] {
        return Aws::MakeShared<Aws::Utils::Logging::ConsoleLogSystem>(
            "console_logger", Aws::Utils::Logging::LogLevel::Trace);
    };
}

int main() {
    // Set and initalise api options
    Aws::SDKOptions options;
    // Initialise logging
    options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Trace;
    options.loggingOptions.logger_create_fn = GetConsoleLoggerFactory();
    
    Aws::InitAPI(options);
    {
        run_handler(my_handler);
    }
    Aws::ShutdownAPI(options);
    return 0;
}
```
I didn't go down the CMake route as I'm not overly familiar with it, but just created my own Makefile with the relevant library links etc. Managed to compile it, upload it and run it both remotely and from within the Lambda UI no problem.

However, I couldn't manage to get any log output from the my_handler method
As a test, commented out run_handler(my_handler), added some AWS_LOGSTREAM_INFO() calls in the codeblock after the InitAPI, compiled and ran the cpp binary locally and the logging worked as expected.

After much head-scratching, googling and trying various things, I tried adding the AWS_LOGSTREAM_FLUSH() function after the AWS_LOGSTREAM_INFO() call in the my_handler function and finally started getting output.

I'm just wondering why flushing the buffer is required here, when you didn't use it in your S3 example and it didn't seemed to be needed when I ran the cpp binary from the command-line using the aws logging libraries?

Apologies if it is a silly question. I'm more familiar with Java than C++, but was trying lambda with the Java runtime and found the cold-start very slow and was looking for a faster alternative.

Any help would be greatly appreciated.

**Comment by jgcrunden** [comment]
After posting this, I had a look through the closed issues for this repo.
I wondering if this is related to #36 ?

**Comment by marcomagdy** [comment]
> After posting this, I had a look through the closed issues for this repo.
> I wondering if this is related to #36 ?

Yes. It's the same issue.
I recommend you call flush once at the end of your function.

**Comment by jgcrunden** [comment]
Thanks Marco.
How large is the buffer? Might it overflow if it is only called once at the end of the lambda?

**Comment by marcomagdy** [comment]
You don't have to worry about that. The SDK flushes the buffer when it hits the limit periodically. Flushing the buffer at the end of your function ensures that any left-overs in the buffer get written to stdout before you exit.
