### ISSUE TITLE
Slimmer archive

### ISSUE THREAD

**Issue by rdettai** [awslabs/aws-lambda-cpp#91]
Disclaimer: I really don't know cmake the c++ build system very well

I wanted to know if it is possible to generate a single well optimized binary (as Rust or Go would) instead of what is generated here: an executable with a bunch of `.so` in a separated `lib/` folder. 

The reason for this request is that I'm very surprised by the size of the generated archives. For the exact same functionality (a few lines of code with only one dependency to the S3 client) the c++ runtime yields a zip file of 14MB and the Rust runtime only 1.9MB...

PS: I have read the Readme section, and I'm not sure to understand, should I use Alpine to use musl libc or Amazon Linux and use provided libc ?

**Comment by marcomagdy** [comment]
The answer is it depends.
If your goal is to have a single binary, you will have to build all your transitive dependencies as static libraries (no small feat in any non-trivial program).

If your goal is to shrink the package, then you could save a few megabytes by not packaging libc. Which as you pointed out can be done either by using `musl` libc (which is significantly smaller than GNU libc) or by building and packaging your code on Amazon Linux and passing the `NO_LIBC` in CMake.

If you want to use musl, all your transitive dependencies must link to musl for that to work. And the easiest way to do that is to use a Linux distro that ships with musl libc as its default (such as Alpine).

Rust, thanks to Cargo, enables its users to build all the dependencies from source and link them statically while using musl for the entire dependency graph. (in C/C++ you have to do that manually as I mentioned above).

Go, does not use any libc implementation.
