### ISSUE TITLE
What happens when deploying statically linked C++ 17 code?

### ISSUE THREAD

**Issue by djinn** [awslabs/aws-lambda-cpp#92]
Hello Lambda team,

I have written a benchmark in C++. An equivalent of [Lambda CPU Cost](https://github.com/jconning/lambda-cpu-cost). It is written in C++ 17 and uses parallel execution models. 

I wanted to check before creating the struts, what are the issues regarding creating C++ 17 binaries deploying on Lambda.

**Comment by marcomagdy** [comment]
There are no issues.
Just follow the instructions in the README.
